# name: Workflow GitHub Action

# # Run Workflow when push on main
# on:
#   push:
#     branches:
#       - master
# jobs:
#   execute:
#     name: Update the production VM
#     runs-on: ubuntu-latest
#     steps:
#     - name: Connecting on remote VM
#       uses: appleboy/ssh-action@master
#       with:
#         host: ${{ secrets.SSH_HOST }}
#         port: ${{ secrets.SSH_PORT }}
#         username: ${{ secrets.SSH_USER }}
#         key: ${{ secrets.SSH_KEY }}
#         script: |
#                   cd /var/www/html/
#                   git pull
#                   make publish